services:
  app:
    build: .
    container_name: contapa2-m1-ws
    volumes:
      - ./website:/var/www/html/website
    ports:
      - 8085:80
      - 4443:443
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: contsql-m1-ws
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped

volumes:
  mysql_db:
