services:
  proxy:
    image: nginx:alpine
    container_name: contproxy-m1-ws
    ports:
      - 8085:80
      - 4443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    restart: unless-stopped

  app:
    build: ./apache2
    volumes:
      - ./website:/var/www/html/website
    env_file:
      - .env
    depends_on:
      - db
      - proxy
    scale: 4
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: contsql-m1-ws
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped

volumes:
  mysql_db:
