services:
  proxy:
    image: nginx:alpine
    container_name: contproxy-m1-ws
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
      - ./lego/certificates:/etc/ssl/certs/
    restart: unless-stopped

  app:
    build: ./apache2
    volumes:
      - ./website:/var/www/html/website
    environment:
      - APACHE_ROOT_DIR={APACHE_ROOT_DIR}
      - APACHE_RUN_DIR={APACHE_RUN_DIR}
      - APACHE_RUN_USER={APACHE_RUN_USER}
      - APACHE_RUN_GROUP={APACHE_RUN_GROUP}
      - APACHE_LOG_DIR={APACHE_LOG_DIR}
      - APACHE_PID_FILE={APACHE_PID_FILE}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
      - proxy
    scale: 4
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: contsql-m1-ws
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped

volumes:
  mysql_db:
