FROM ubuntu:24.04
# RUN useradd -m contapa2-m1-ws
EXPOSE 80
RUN apt-get update && apt-get install -y apache2 && mkdir -p /var/run/apache2 && chown www-data:www-data /var/run/apache2
COPY ./apache2/apache2.conf /etc/apache2/apache2.conf
COPY ./apache2/ports.conf /etc/apache2/
COPY ./apache2/000-default.conf /etc/apache2/sites-available
COPY ./website/ /var/www/html/

ENV APACHE_RUN_DIR=/var/run/apache2, APACHE_RUN_USER=www-data, APACHE_RUN_GROUP=www-data, APACHE_LOG_DIR=/var/log/apache2, APACHE_PID_FILE=/var/run/apache2/apache2.pid

CMD apache2 -S
