FROM ubuntu:24.04

EXPOSE 80
EXPOSE 443

RUN apt-get update && apt-get install -y apache2 && mkdir -p /var/run/apache2 && chown www-data:www-data /var/run/apache2
COPY ./apache2/apache2.conf /etc/apache2/apache2.conf
COPY ./apache2/ports.conf /etc/apache2/ports.conf
COPY ./apache2/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./apache2/default-ssl.conf /etc/apache2/sites-available/default-ssl.conf

CMD apache2 -D FOREGROUND
