FROM ubuntu:24.04

EXPOSE 80
RUN apt-get update && apt-get install -y apache2 && mkdir -p /var/run/apache2 && chown www-data:www-data /var/run/apache2
COPY ./apache2/apache2.conf /etc/apache2/apache2.conf
COPY ./apache2/ports.conf /etc/apache2/
COPY ./apache2/000-default.conf /etc/apache2/sites-available
COPY ./website/ /var/www/html/

CMD apache2 -D FOREGROUND
